#!/usr/bin/env bash

echo "The script is running..."   # debug

local software="az"

if [ -f "../${software}/available_versions" ]
then
  doEcho "Print available_versions:"        # debug
  cat "../${software}/available_versions"
else
  doEcho "Getting available versions..."    # debug
  versions_url=$(cat "../${software}/versions-url")
  versions_url_op=$(cat "../${software}/versions-url-op")
  if [ "${versions_url_op}" == "github" ]
  then
    curl "${versions_url}" | awk -F "\"" '/tag_name/ {print $4}' | sort -V -r > "../${software}/available_versions"
  else 
    eval "curl "${versions_url}" | "${versions_url_op}"" > "../${software}/available_versions"
  fi
  cat "../${software}/available_versions"
fi
