#!/usr/bin/env bash

for software in */;
do
  if [ "${software}" = "gradle/" ]
  then
    software=${software::-1}
    versions_url="./${software}/versions-url"
    versions_url_op="./${software}/versions-url-op"
    subdir_count=$(find "./${software}" -maxdepth 1 -type d | wc -l)

    if [ "${subdir_count}" -eq 1 ]
    then
      if grep -q "api.github.com" "${versions-url}"
      then
        curl -s "${versions_url}" | awk -F "\"" '/tag_name/ {print $4}' | sort -V -r > "./${software}/available_versions"
      else 
        eval "curl -s "${versions_url}" | "${versions_url_op}"" > "./${software}/available_versions"
      fi
    else
      echo "Subdirectories for providers present."
    fi
  fi
done
