#!/usr/bin/env bash

for software in */;
do
  if [ "${software}" = "aws/" ]
  then
    software=${software::-1}
    subdir_count=$(find "./${software}" -maxdepth 1 -type d | wc -l)
    chmod +x ./${software}/*

    if [ "${subdir_count}" -eq 1 ]
    then
      versions_url=$(cat "./${software}/versions-url")
      versions_url_op=$(cat "./${software}/versions-url-op")

      if [[ "${versions_url}" == *"api.github"* ]]
      then
        curl -s "${versions_url}" | awk -F "\"" '/tag_name/ {print $4}' | sort -V -r > "./${software}/available_versions"
      else
        eval "curl -s "${versions_url}" | "${versions_url_op}"" > "./${software}/available_versions"
      fi
    else
      for subdir in ./${software}/*/;
      do
        subdir=$(basename "${subdir}")
        versions_url=$(cat "./${software}/${subdir}/versions-url")
        versions_url_op=$(cat "./${software}/${subdir}/versions-url-op")

        echo "${subdir}" >> "./${software}/available_versions.tmp"

        if [[ "${versions_url}" == *"api.github"* ]]
        then
          curl -s "${versions_url}" | awk -F "\"" '/tag_name/ {print $4}' | sort -V -r >> "./${software}/available_versions.tmp"
        else 
          eval "curl -s "${versions_url}" | "${versions_url_op}"" >> "./${software}/available_versions.tmp"
        fi
        echo "======" >> "./${software}/available_versions.tmp"
      done
      mv "./${software}/available_versions.tmp" "./${software}/available_versions"
    fi
    # debug
    echo "Available versions:"
    cat "./${software}/available_versions"
  fi
done
